### PR TITLE
fix facter no longer working on puppet 7

### LINKED ISSUE #190: facter -p no longer supported with Puppet 7
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7
- Ruby:
- Distribution: CentOS 7
- Module version: 0.13

## How to reproduce (e.g Puppet code you use)

just use puppet 7 and the cron, will send an email to root with the warning below. 

## What are you seeing

[2021-01-19 12:21:08.897275 ] WARN Facter::Cli - `facter --puppet` and `facter -p` are no longer supported, use `puppet facts show` instead 
[2021-01-19 12:21:08.897321 ] WARN Facter::Cli - the output does not contain puppet facts! 

## Any additional information you'd like to impart

I wonder if `puppet facts show` is backward compatible, or you may need to run something as following: 

```bash
if [ $(puppet --version|cut -d. -f1) -gt 5 ]; then
    ....
fi
```

with the problem being, `puppet facts` throws a json or yaml objest instead of the value

### PR DESCRIPTION
**Pull request by maxadamo**
resolves #190

### CODE REVIEW

File: files/os_patching_fact_generation.sh [hunk 1]
```diff
@@ -17,7 +17,17 @@ else
   echo "$$" > $LOCKFILE
 fi
 
-case $(facter osfamily) in
+if [ $(puppet --version|cut -d. -f1) -gt 6 ]; then
+  OSFAMILY=$(puppet facts show --render-as s osfamily | cut -d\" -f4)
+  VARDIR=$(puppet facts show --render-as s puppet_vardir | cut -d\" -f4)
```
Comment (TJM) [inline files/os_patching_fact_generation.sh:22]: That seems like it should be a `puppet config print vardir` ?

Comment (maxadamo) [reply files/os_patching_fact_generation.sh:22]: > That seems like it should be a `puppet config print vardir` ?

Thanks. I am gonna change it. It's less consistent in the whole script, but it's quicker to execute.

Comment (TJM) [reply files/os_patching_fact_generation.sh]: I saw both methods in there too... thats where I got the idea, thinking "vardir" really sounds more like a config than a fact. I am pretty sure osfamily and stuff will still need to be gathered as facts. Another "point of interest" is that I think "osfamily" is a *legacy* fact that was deprecated? Perhaps we should go with os.family (structured fact)? (and I am sure there are others like that?)
